### ISSUE TITLE
Inventory Desync when using bungeecord

### ISSUE THREAD

**Issue by kriNon** [trentech/ProjectInventories#10]
Hey, I am trying to use project inventories on a couple of local servers with bungeecord (waterfall) as a proxy to switch between servers. It seems that after switching back and forth between the two servers a few times the player inventories will desync. I believe this might be happening because when swapping between the two servers it will swap before the mysql server has finished updating although I am not certain this is the cause. I am also getting a lot of errors in my server terminal. Whilst I do believe this is a problem that is easily reproducable using bungeecord, I do believe that theoretically it could happen on two regular servers if the connection to the mysql server is severely slowed.

Any help would be much appreciated!

[02:12:26] [Netty Server IO #4/INFO] [FML]: Client protocol version 2
[02:12:26] [Netty Server IO #4/INFO] [FML]: Client attempting to join with 10 mo
ds : CodeChickenLib@2.5.0.180,nbtedit@$version,NotEnoughItems@2.1.3.179,CodeChic
kenCore@2.4.0.100,FML@8.0.99.99,Forge@12.18.2.2171,chiselsandbits@12.8,mcp@9.19,
ccl-entityhook@1.0,JEI@3.13.6.391
[02:12:26] [Netty Server IO #4/INFO] [FML]: Attempting connection with missing m
ods [spongeapi, sponge, pji] at CLIENT
[02:12:26] [Server thread/INFO] [FML]: [Server thread] Server side modded connec
tion established
[02:12:26] [Server thread/INFO]: kriNon[/127.0.0.1:31156] logged in with entity
id 533 in world(0) at (140.49541408269974, 65.0, 213.09077124949306)
[02:12:26] [Server thread/INFO]: kriNon joined the game
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]: java.lang.NullPointerException
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.io.StringReader.<init>(Unknown Source)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.data.PlayerInventoryDa
ta.deserialize(PlayerInventoryData.java:383)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.sql.PlayerDB$Data.get(
PlayerDB.java:175)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.settings.PlayerSetting
s.get(PlayerSettings.java:42)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.settings.PlayerSetting
s.set(PlayerSettings.java:129)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.settings.PlayerSetting
s.set(PlayerSettings.java:117)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.EventManager.lambda$Cl
ientConnectionEventJoin$0(EventManager.java:44)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at org.spongepowered.common.scheduler.SchedulerB
ase.lambda$startTask$0(SchedulerBase.java:183)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.Executors$RunnableAdapte
r.call(Unknown Source)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.FutureTask.run(Unknown S
ource)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.ThreadPoolExecutor.runWo
rker(Unknown Source)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.ThreadPoolExecutor$Worke
r.run(Unknown Source)
[02:12:28] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.lang.Thread.run(Unknown Source)
[02:12:28] [pool-4-thread-1/ERROR] [Sponge]: The Scheduler tried to run the task
 pji-A-44 owned by Plugin{id=pji, name=ProjectInventories, version=0.10.0, descr
iption=Multi world inventories, url=http://github.com/TrenTech/ProjectInventorie
s, authors=[TrenTech], source=D:\Kris's Workbench\Minecraft Modpack\Minecraft Mo
dpack MMO\Server1\mods\projectinventories-5.1.0-0.10.0.jar}, but an error occure
d.
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_91]
        at java.util.Optional.<init>(Unknown Source) ~[?:1.8.0_91]
        at java.util.Optional.of(Unknown Source) ~[?:1.8.0_91]
        at com.gmail.trentech.pji.sql.PlayerDB$Data.get(PlayerDB.java:179) ~[Pla
yerDB$Data.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.get(PlayerSettings.jav
a:42) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.jav
a:129) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.jav
a:117) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.EventManager.lambda$ClientConnectionEventJoin$
0(EventManager.java:44) ~[EventManager.class:?]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(S
chedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2171-5.1.0-BETA-1992]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[02:12:34] [Server thread/INFO]: kriNon lost connection: Disconnected
[02:12:34] [Server thread/INFO]: kriNon left the game
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]: java.lang.IllegalArgumentException: Configuration does n
ot accept objects of type class [I
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.ScalarConfigValue.s
etValue(ScalarConfigValue.java:42)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.SimpleConfiguration
Node.insertNewValue(SimpleConfigurationNode.java:274)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.SimpleConfiguration
Node.setValue(SimpleConfigurationNode.java:201)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.commented.SimpleCom
mentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:74)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.commented.SimpleCom
mentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:32)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.SimpleConfiguration
Node.setValue(SimpleConfigurationNode.java:182)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.commented.SimpleCom
mentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:74)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.commented.SimpleCom
mentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:32)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.SimpleConfiguration
Node.setValue(SimpleConfigurationNode.java:182)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.commented.SimpleCom
mentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:74)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.commented.SimpleCom
mentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:32)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at org.spongepowered.common.config.DataSerializa
bleTypeSerializer.serialize(DataSerializableTypeSerializer.java:52)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at org.spongepowered.common.config.DataSerializa
bleTypeSerializer.serialize(DataSerializableTypeSerializer.java:40)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.ConfigurationNode.s
etValue(ConfigurationNode.java:402)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at com.gmail.trentech.pji.utils.ItemSerializer.s
erialize(ItemSerializer.java:22)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at com.gmail.trentech.pji.data.PlayerInventoryDa
ta.toContainer(PlayerInventoryData.java:267)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at org.spongepowered.common.config.DataSerializa
bleTypeSerializer.serialize(DataSerializableTypeSerializer.java:52)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at org.spongepowered.common.config.DataSerializa
bleTypeSerializer.serialize(DataSerializableTypeSerializer.java:40)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at ninja.leaping.configurate.ConfigurationNode.s
etValue(ConfigurationNode.java:402)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at com.gmail.trentech.pji.data.PlayerInventoryDa
ta.serialize(PlayerInventoryData.java:372)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at com.gmail.trentech.pji.sql.PlayerDB$Data.lamb
da$update$1(PlayerDB.java:242)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at org.spongepowered.common.scheduler.SchedulerB
ase.lambda$startTask$0(SchedulerBase.java:183)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at java.util.concurrent.Executors$RunnableAdapte
r.call(Unknown Source)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at java.util.concurrent.FutureTask.run(Unknown S
ource)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at java.util.concurrent.ThreadPoolExecutor.runWo
rker(Unknown Source)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at java.util.concurrent.ThreadPoolExecutor$Worke
r.run(Unknown Source)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.utils.ItemSe
rializer:serialize:26]:         at java.lang.Thread.run(Unknown Source)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]: java.lang.NullPointerException: value
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at com.google.common.base.Preconditions.checkNot
Null(Preconditions.java:229)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at org.spongepowered.api.data.MemoryDataView.set
(MemoryDataView.java:229)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at org.spongepowered.api.data.MemoryDataView.set
Map(MemoryDataView.java:396)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at org.spongepowered.api.data.MemoryDataView.set
(MemoryDataView.java:277)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at org.spongepowered.api.data.MemoryDataContaine
r.set(MemoryDataContainer.java:61)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at com.gmail.trentech.pji.data.PlayerInventoryDa
ta.toContainer(PlayerInventoryData.java:270)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at org.spongepowered.common.config.DataSerializa
bleTypeSerializer.serialize(DataSerializableTypeSerializer.java:52)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at org.spongepowered.common.config.DataSerializa
bleTypeSerializer.serialize(DataSerializableTypeSerializer.java:40)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at ninja.leaping.configurate.ConfigurationNode.s
etValue(ConfigurationNode.java:402)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at com.gmail.trentech.pji.data.PlayerInventoryDa
ta.serialize(PlayerInventoryData.java:372)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at com.gmail.trentech.pji.sql.PlayerDB$Data.lamb
da$update$1(PlayerDB.java:242)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at org.spongepowered.common.scheduler.SchedulerB
ase.lambda$startTask$0(SchedulerBase.java:183)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at java.util.concurrent.Executors$RunnableAdapte
r.call(Unknown Source)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at java.util.concurrent.FutureTask.run(Unknown S
ource)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at java.util.concurrent.ThreadPoolExecutor.runWo
rker(Unknown Source)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at java.util.concurrent.ThreadPoolExecutor$Worke
r.run(Unknown Source)
[02:12:34] [pool-4-thread-1/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:serialize:376]:    at java.lang.Thread.run(Unknown Source)
[02:14:10] [Netty Server IO #5/INFO] [FML]: Client protocol version 2
[02:14:10] [Netty Server IO #5/INFO] [FML]: Client attempting to join with 10 mo
ds : CodeChickenLib@2.5.0.180,nbtedit@$version,NotEnoughItems@2.1.3.179,CodeChic
kenCore@2.4.0.100,FML@8.0.99.99,Forge@12.18.2.2171,chiselsandbits@12.8,mcp@9.19,
ccl-entityhook@1.0,JEI@3.13.6.391
[02:14:10] [Netty Server IO #5/INFO] [FML]: Attempting connection with missing m
ods [spongeapi, sponge, pji] at CLIENT
[02:14:10] [Server thread/INFO] [FML]: [Server thread] Server side modded connec
tion established
[02:14:10] [Server thread/INFO]: kriNon[/127.0.0.1:31163] logged in with entity
id 535 in world(0) at (148.3706900594704, 62.0, 201.6330783980419)
[02:14:10] [Server thread/INFO]: kriNon joined the game
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]: java.lang.NullPointerException
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.io.StringReader.<init>(Unknown Source)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.data.PlayerInventoryDa
ta.deserialize(PlayerInventoryData.java:383)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.sql.PlayerDB$Data.get(
PlayerDB.java:175)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.settings.PlayerSetting
s.get(PlayerSettings.java:42)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.settings.PlayerSetting
s.set(PlayerSettings.java:129)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.settings.PlayerSetting
s.set(PlayerSettings.java:117)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at com.gmail.trentech.pji.EventManager.lambda$Cl
ientConnectionEventJoin$0(EventManager.java:44)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at org.spongepowered.common.scheduler.SchedulerB
ase.lambda$startTask$0(SchedulerBase.java:183)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.Executors$RunnableAdapte
r.call(Unknown Source)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.FutureTask.run(Unknown S
ource)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.ThreadPoolExecutor.runWo
rker(Unknown Source)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.util.concurrent.ThreadPoolExecutor$Worke
r.run(Unknown Source)
[02:14:12] [pool-4-thread-6/INFO] [STDERR]: [com.gmail.trentech.pji.data.PlayerI
nventoryData:deserialize:388]:  at java.lang.Thread.run(Unknown Source)
[02:14:12] [pool-4-thread-6/ERROR] [Sponge]: The Scheduler tried to run the task
 pji-A-47 owned by Plugin{id=pji, name=ProjectInventories, version=0.10.0, descr
iption=Multi world inventories, url=http://github.com/TrenTech/ProjectInventorie
s, authors=[TrenTech], source=D:\projectinventories-5.1.0-0.10.0.jar}, but an error occure
d.
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_91]
        at java.util.Optional.<init>(Unknown Source) ~[?:1.8.0_91]
        at java.util.Optional.of(Unknown Source) ~[?:1.8.0_91]
        at com.gmail.trentech.pji.sql.PlayerDB$Data.get(PlayerDB.java:179) ~[Pla
yerDB$Data.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.get(PlayerSettings.jav
a:42) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.jav
a:129) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.jav
a:117) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.EventManager.lambda$ClientConnectionEventJoin$
0(EventManager.java:44) ~[EventManager.class:?]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(S
chedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2171-5.1.0-BETA-1992]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
>

**Comment by trentech** [comment]
please use pastebin or similar service for errors. This is near impossible to read and comprehend.

**Comment by kriNon** [comment]
Sorry about that, I have put the text on pastebin now.

**Comment by trentech** [comment]
Hmm, looks like the database is returning null. Not the error I was expecting. Could be related to the de-sync issue but now sure. I've struggled with this before but thought I has fix it. It's hard to test because it all depends on server specs, load, bandwidth and what have you. Originally I just set a delay on setting inventory on server join, which seemed to work during my tests but had a feeling a busy server might cause the problem to re-occur. When I get some time I'll look into this.

**Comment by kriNon** [comment]
You mentioned that you have a delay upon setting inventory on server join, couldn't that result in the player joining and quickly dropping their items before server syncing, effectively duplicating items?

**Comment by trentech** [comment]
Possible but not likely. They'd have to do a ninja move to pull it off and from tests it usually took longer to fully load the Player than the delay took. If it does turn out to be possible I can fix it. I'll put that on my to do list.

Honestly I don't like doing a delay at all but I don't know any other way to prevent the desync issues.

**Comment by kriNon** [comment]
I'll test it out later to see if I can do it, but would it be possible to wipe the players inventory upon log off (only on the Minecraft server, not the mysql server) so that upon log on the player has an empty inventory until the sync occurs.

**Comment by kriNon** [comment]
Yeah I did test it, I was able to quite easily reproduce this by switching between the two servers I am running and pressing "Q" to drop the item as soon as I log in. This was done with two locally hosted servers. I was even able to pull it off without bungee, by just logging into one of the servers and spamming "Q".

Maybe I should open a new issue for this to keep it separate from the other issue?

**Comment by trentech** [comment]
Well crap. Yeah I can fix that. Your suggestion was actually what I had in mind.

**Comment by trentech** [comment]
So I've quickly through together some changes while I have a few minutes. I have not been able to test them so I'm not going to submit them yet, but when here is a dev build. I'm hoping this will help. Inventory should clear on logout after it is saved to the database. I've also changed the delay to be configurable if server is using MySQL. Let me know if this works, I don't have enough time to setup a Bungee server right now.

https://www.dropbox.com/s/mfvv87492ua5vu2/projectinventories-5.1.0-0.10.0-dev2.jar?dl=0

**Comment by kriNon** [comment]
hmm, not sure if I am doing something wrong but it doesn't seem like the inventories are syncing at all any more, each server keeps their own inventory (which should be getting wiped upon logoff), so I guess it partially works? Since each server is able to keep the inventory after logoff i'd assume that means that some of the changes you made work, no idea why it wouldn't work across the two servers though, i'll do some testing and try to figure it out.

**Comment by trentech** [comment]
Please retest these problems with latest release.
