### ISSUE TITLE
NullPointerException error

### ISSUE THREAD

**Issue by bhi-elliot** [trentech/ProjectInventories#25]
```
[pool-2-thread-1384/INFO]: [STDERR]: java.lang.NullPointerException
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at java.io.StringReader.<init>(Unknown Source)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at com.gmail.trentech.pji.data.PlayerInventoryData.deserialize(PlayerInventoryData.java:441)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at com.gmail.trentech.pji.sql.PlayerDB$Data.get(PlayerDB.java:187)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at com.gmail.trentech.pji.settings.PlayerSettings.get(PlayerSettings.java:43)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.java:130)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.java:118)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at com.gmail.trentech.pji.EventManager.lambda$ClientConnectionEventJoin$2(EventManager.java:172)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:187)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at java.util.concurrent.FutureTask.run(Unknown Source)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:44:41] [pool-2-thread-1384/INFO]: [STDERR]:         at java.lang.Thread.run(Unknown Source)
[13:44:41] [pool-2-thread-1384/ERROR] [Sponge]: The Scheduler tried to run the task pji-A-2010 owned by Plugin{id=pji, name=Project Inventories, version=0.11.0, description=Multi world inventories, url=http://github.com/TrenTech/ProjectInventories, authors=[TrenTech], source=C:\Minecraft_Server\mods\project inventories-6.1.0-0.11.0 b19.jar}, but an error occured.
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_131]
        at java.util.Optional.<init>(Unknown Source) ~[?:1.8.0_131]
        at java.util.Optional.of(Unknown Source) ~[?:1.8.0_131]
        at com.gmail.trentech.pji.sql.PlayerDB$Data.get(PlayerDB.java:191) ~[PlayerDB$Data.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.get(PlayerSettings.java:43) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.java:130) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.settings.PlayerSettings.set(PlayerSettings.java:118) ~[PlayerSettings.class:?]
        at com.gmail.trentech.pji.EventManager.lambda$ClientConnectionEventJoin$2(EventManager.java:172) ~[EventManager.class:?]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:187) ~[SchedulerBase.class:1.11.2-2393-6.1.0-BETA-2468]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by fusionmc-evilscoop** [comment]
Im also getting this....
Would love to see some new releases of this mod...I really need it for the server

**Comment by trentech** [comment]
This issue was already resolved

http://trentech.org/jenkins/job/ProjectInventories%20for%20SpongeAPI%207.x/25/
