### ISSUE TITLE
How to set up?

### ISSUE THREAD

**Issue by ziceptor** [trentech/ProjectInventories#29]
The plugin works with nucleus (module world)?
How to prevent players to transfer inventories between worlds?

I have two of the world:
ziCraft <-- skyblock (survival)
custom <-- survival

So?
```
/inv c custom
/inv c zicraft
/inv a custom CUSTOM t <-- error (https://gist.github.com/ziceptor/57cc994987c42ba024aada3762a0c6cb)
/inv a ziCRAFT ZICRAFT t <-- error ^
```

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2732.jar
projectinventories-7.0.0-0.11.0.jar

**Comment by jh1226** [comment]
I got something like this:
> Error occurred while executing command 'inventory add Survival SURVIVAL true' for source EntityPlayerMP['jh1226'/736, l='Survival', x=-180.76, y=79.00, z=163.76]: null
java.lang.UnsupportedOperationException: null
        at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:473) ~[minecraft_server.1.12.2.jar:?]
        at com.gmail.trentech.pji.data.WorldData.add(WorldData.java:51) ~[WorldData.class:?]
        at com.gmail.trentech.pji.commands.CMDAdd.execute(CMDAdd.java:57) ~[CMDAdd.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:181) ~[ChildCommandElementExecutor.class:1.12.2-2529-7.0.0-BETA-2736]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-2529-7.0.0-BETA-2736]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2529-7.0.0-BETA-2736]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-2529-7.0.0-BETA-2736]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2529-7.0.0-BETA-2736]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zke000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:272) [SpongeImplHooks.class:1.12.2-2529-7.0.0-BETA-2736]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zig000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by ziceptor** [comment]
Any news?

**Comment by ziceptor** [comment]
Howto: "/helpme inventory" :)
