### ISSUE TITLE
Unable to translate object to JSON

### ISSUE THREAD

**Issue by ziceptor** [trentech/ProjectInventories#36]
https://gist.github.com/ziceptor/fe8abf93937f674f43dfd0e1b617c86c

**Comment by kencinder** [comment]
Same problem here

https://pastebin.com/qsA3SBin

**Comment by Big-Deaddy** [comment]
I'm having the same issue, but I've received several different errors, eventually leading to a server crash if the player stayed on the server for long enough:
https://gist.github.com/Big-Deaddy/1e8b4e61c16db8481e2325f989152985
https://gist.github.com/Big-Deaddy/f19bfcf232392f046cdaa8eede0f5c8d
https://gist.github.com/Big-Deaddy/d40223159f58adc4c978de6d564f45cc

All of these issues seem to be connected to fireworks. 

If someone joins the server with fireworks already in their inventory, they will be spammed with "Please wait while inventory is updated", and the console will spam with the errors listed above. If the firework is removed, the console spam will stop, but the user will continue to be spammed until the server is restarted.

If someone joins and a firework is added to their inventory, it will cause console spam, but the user won't get any messages. If they leave and rejoin, their inventory will revert back to the last time it was saved before the firework was added.

Sponge version: 2705
Project Inventories version: 0.11.2
Project Core version: 0.2.1

**Comment by Simba98** [comment]
do you think this is a bug by Sponge?

java.lang.IllegalArgumentException: Unable to translate object to JSON: [I@1c01add6
	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:223) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.writeMap(JsonDataFormat.java:245) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:217) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.writeMap(JsonDataFormat.java:245) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:217) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.writeMap(JsonDataFormat.java:245) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:217) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.writeView(JsonDataFormat.java:199) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.writeTo(JsonDataFormat.java:190) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:183) ~[JsonDataFormat.class:1.12.2-2768-7.1.4]
	at com.gmail.trentech.pji.data.PlayerInventoryData.toContainer(PlayerInventoryData.java:253) ~[PlayerInventoryData.class:?]
	at com.gmail.trentech.pji.data.PlayerInventoryData.serialize(PlayerInventoryData.java:446) ~[PlayerInventoryData.class:?]
	at com.gmail.trentech.pji.sql.PlayerDB$Data.update(PlayerDB.java:261) ~[PlayerDB$Data.class:?]
	at com.gmail.trentech.pji.settings.PlayerSettings.save(PlayerSettings.java:97) ~[PlayerSettings.class:?]
	at com.gmail.trentech.pji.EventManager.onSaveWorldEvent(EventManager.java:270) ~[EventManager.class:?]

It seems like PJI called JsonDataFormat.write and this sponge function throw Unable to translate object to JSON.

PJI just simple transfer player object to sponge function.
Like this repo : https://github.com/trentech/ProjectInventories/blob/fa9ad8065092e9aea7289f322e6f5a36601f5eda/src/main/java/com/gmail/trentech/pji/data/PlayerInventoryData.java
Line 242:
	DataContainer container = DataContainer.createNew().set(NAME, this.name).set(OFF_HAND, this.offHand.toContainer()).set(HELMET, this.helmet.toContainer())

				.set(CHEST_PLATE, this.chestPlate.toContainer()).set(LEGGINGS, this.leggings.toContainer()).set(BOOTS, this.boots.toContainer());

PJI just simple get all objects and transfer to this.someblabla.toContainer().
