### ISSUE TITLE
Plugin uses SQL When configured not to.

### ISSUE THREAD

**Issue by Sven65** [trentech/ProjectInventories#41]
Crashes the server.
Stacktrace is as follows:

```
[22:32:49 ERROR] [STDERR]: INSERT into `PJI.INV.WORLD` (UUID, Data) VALUES (?, ?) [42102-196]
[22:32:49 ERROR] [STDERR]:      at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[22:32:49 ERROR] [STDERR]:      at org.h2.message.DbException.get(DbException.java:179)
[22:32:49 ERROR] [STDERR]:      at org.h2.message.DbException.get(DbException.java:155)
[22:32:49 ERROR] [STDERR]:      at org.h2.command.Parser.readTableOrView(Parser.java:5552)
[22:32:49 ERROR] [STDERR]:      at org.h2.command.Parser.readTableOrView(Parser.java:5529)
[22:32:49 ERROR] [STDERR]:      at org.h2.command.Parser.parseInsert(Parser.java:1062)
[22:32:49 ERROR] [STDERR]:      at org.h2.command.Parser.parsePrepared(Parser.java:417)
[22:32:49 ERROR] [STDERR]:      at org.h2.command.Parser.parse(Parser.java:321)
[22:32:49 ERROR] [STDERR]:      at org.h2.command.Parser.parse(Parser.java:293)
[22:32:49 ERROR] [STDERR]:      at org.h2.command.Parser.prepareCommand(Parser.java:258)
[22:32:49 ERROR] [STDERR]:      at org.h2.engine.Session.prepareLocal(Session.java:578)
[22:32:49 ERROR] [STDERR]:      at org.h2.engine.Session.prepareCommand(Session.java:519)
[22:32:49 ERROR] [STDERR]:      at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
[22:32:49 ERROR] [STDERR]:      at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
[22:32:49 ERROR] [STDERR]:      at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
[22:32:49 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:312)
[22:32:49 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[22:32:49 ERROR] [STDERR]:      at com.gmail.trentech.pji.sql.PlayerDB$Data.create(PlayerDB.java:239)
[22:32:49 ERROR] [STDERR]:      at com.gmail.trentech.pji.settings.PlayerSettings.save(PlayerSettings.java:99)
[22:32:49 ERROR] [STDERR]:      at com.gmail.trentech.pji.EventManager.onSaveWorldEvent(EventManager.java:270)
[22:32:49 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.SaveWorldEventListener_EventManager_onSaveWorldEvent90.handle(Unknown Source)
[22:32:49 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[22:32:49 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:433)
[22:32:49 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:478)
[22:32:49 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465)
[22:32:49 ERROR] [STDERR]:      at net.minecraft.world.WorldServer.func_73044_a(SourceFile:2270)
[22:32:49 ERROR] [STDERR]:      at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:542)
[22:32:49 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.func_71267_a(SourceFile:4052)
[22:32:49 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zji000(SourceFile:4005)
[22:32:49 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:575)
[22:32:49 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:464)
[22:32:49 ERROR] [STDERR]:      at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sven65** [comment]
After that, it crashes the server with 

```
[22:35:00 ERROR] [STDERR]: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30000ms.
[22:35:00 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
[22:35:00 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[22:35:00 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
[22:35:00 ERROR] [STDERR]:      at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[22:35:00 ERROR] [STDERR]:      at com.gmail.trentech.pji.sql.PlayerDB$Data.create(PlayerDB.java:237)
[22:35:00 ERROR] [STDERR]:      at com.gmail.trentech.pji.settings.PlayerSettings.save(PlayerSettings.java:99)
[22:35:00 ERROR] [STDERR]:      at com.gmail.trentech.pji.EventManager.onSaveWorldEvent(EventManager.java:270)
[22:35:00 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.SaveWorldEventListener_EventManager_onSaveWorldEvent90.handle(Unknown Source)
[22:35:00 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[22:35:00 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:433)
[22:35:00 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:478)
[22:35:00 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465)
[22:35:00 ERROR] [STDERR]:      at net.minecraft.world.WorldServer.func_73044_a(SourceFile:2270)
[22:35:00 ERROR] [STDERR]:      at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:542)
[22:35:00 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.func_71267_a(SourceFile:4052)
[22:35:00 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zji000(SourceFile:4005)
[22:35:00 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:575)
[22:35:00 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:464)
[22:35:00 ERROR] [STDERR]:      at java.lang.Thread.run(Thread.java:748)
```

**Comment by nacjm** [comment]
yep got that last one spamming my server also log:https://gist.github.com/nacjm/4d7fc97f5c60af89016c7c0f9f4a42f8
